export const REPORT_SECTIONS = [
  "SUMMARY",
  "VIRAL REASON",
  "KEY MOMENT",
  "TITLE IDEAS",
  "HOOKS",
  "HASHTAGS",
  "CLIP IDEAS",
  "REMIX IDEAS",
  "REACTION SCRIPT",
  "MEME TEMPLATES",
  "PREDICTED LONGEVITY",
  "VIRALITY SCORE",
  "WHAT TO FIX",
  "PLATFORM STRATEGY",
  "CONTENT ANGLE VARIATIONS",
  "TARGET AUDIENCE FIT",
  "FORMAT CLASSIFICATION",
  "REPLICATION FRAMEWORK",
] as const;

export type ReportSectionKey = typeof REPORT_SECTIONS[number];
